name: Test

on: push

jobs:
  phpcs:
    name: PHP Coding Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v2"
      - name: Coding Standards
        run: composer phpcs
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v2"
      - name: Install Composer build dependencies
        run: composer bin build install --no-progress
      - name: Compose dependencies
        run: composer compose
      - name: Analyze
        run: composer phpstan
  phplint:
    name: PHP Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v2"
      - name: Install Composer build dependencies
        run: composer bin build install --no-progress
      - name: Compose dependencies
        run: composer compose
      - name: Lint
        run: composer phplint
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1']
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wp_phpunit_tests
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Setup PHP 7.4
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Composer version
        run: composer self-update --2.2
      - name: Install Composer dependencies
        uses: "ramsey/composer-install@v2"
      - name: Install Composer build dependencies
        run: composer bin build install --no-progress
      - name: Compose dependencies
        run: composer compose
      - name: Remove unused dependencies
        run: composer remove --dev szepeviktor/phpstan-wordpress
      - name: Setup PHP ${{ matrix.php }}
        # https://github.com/shivammathur/setup-php/issues/446#issuecomment-824001225
        uses: shivammathur/setup-php@develop
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none
          tools: none
      - name: PHPUnit
        env:
          WP_DB_HOST: 127.0.0.1:${{ job.services.mysql.ports['3306'] }}
        run: composer phpunit
  css:
    name: CSS Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install Node dependencies
        uses: bahmutov/npm-install@v1
      - name: CSS lint
        run: yarn lint:css
  js:
    name: JS Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install Node dependencies
        uses: bahmutov/npm-install@v1
      - name: JS lint
        run: yarn lint:js
