name: Test

on: pull_request

jobs:
  phpcs:
    name: WordPress Coding Standards
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: composer install --no-progress
    - name: Coding Standards
      run: composer phpcs
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.0', '7.1', '7.2', '7.3', '7.4']
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: composer install --no-progress
    - name: PHPUnit
      run: |
        composer setup-local-tests
        composer phpunit
  css:
    name: CSS Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: CSS lint
      run: |
        yarn install --no-progress
        yarn lint:css
  js:
    name: JS Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: JS lint
      run: |
        yarn install --no-progress
        yarn lint:js
